# Use an official Node.js runtime as a parent image
FROM node:20

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json from the server folder
COPY server/package*.json ./ 

# Install dependencies
RUN npm install

# Copy the rest of your application code to the container
COPY server/ .  

# Expose the port your app will run on
EXPOSE 8000

# Run the application
CMD ["node", "index.js"]
